Enhance/work
SIT-DigiCre/digicore_v3_frontend pull request #61
Opened 2022-10-10 02:09 UTC by MogamiTsuchikawa

## 概要

- [ ] Workの編集機能
- [ ] Work一覧のデザイン改善
- [ ] myworkページ

## スクリーンショット（変更の場合は変更前と変更後が分かるように）

## 破壊的変更があるか(あれば内容を記載)

- [ ] YES
- [x] NO

## チェック項目

- [ ] ビルドが通る
- [ ] 作成した機能が想定通りに動作する
- [ ] スマートフォンサイズで表示確認を行った
- [ ] warning が増えていない
- [ ] 複雑なコードにはコメントを記載してある

2022-10-12 14:13 UTC, Shimiiy reviewed
### レビューできたこと
- **Typo（スペルミス）あるよ**
  - `hook/work/useWork.ts 66行目` autherID → _authorID_ に変えてほしい…！
- WorkページのUI、良さげ
  - worksの列挙処理をコメントアウトで除外したので確認できた
  - Work一覧と新規Workが対をなしているの、わかりやすい
![スクリーンショット 2022-10-12 230411](https://user-images.githubusercontent.com/64347376/195365923-446318a0-8069-4bb6-8699-5a5a17f3f4cf.png)

#### 一個前のコメントも確認してほしいです、放置したら今後バグの温床になりそうな気がするので

2022-10-12 14:50 UTC, Shimiiy reviewed
うーん治らん… worksが存在するか否かの判定が上手く行っていない…？
###### （自分でDBに直接値を入れた方が早い気がしてきた）
![スクリーンショット 2022-10-12 234822](https://user-images.githubusercontent.com/64347376/195375283-81c04ad5-5262-4cb6-8341-5f7dc1aec564.png)

2022-10-12 17:20 UTC, MogamiTsuchikawa commented
こっちでもDB吹き飛ばして無い状態でアクセスしてみたんですが、治っているんですよね
![image](https://user-images.githubusercontent.com/30793866/195407446-dd206b1e-252a-461f-b1a4-f4cbd0d0ff6a.png)
しっかりと最新の内容がpullできているか、バックエンド側はしっかりと最新のMaster＆DB構造も最新か（Migrationしてあるか）など再確認お願いします

2022-10-14 02:48 UTC, MogamiTsuchikawa commented
@Shimiiy Avatar表示できるようにした
![image](https://user-images.githubusercontent.com/30793866/195750824-2c65c42e-b9e0-4645-96a3-1865c01d3703.png)

2022-10-14 03:00 UTC, MogamiTsuchikawa commented
これで変更満足できました

2022-10-14 03:07 UTC, Shimiiy commented
つい30分前までは Work一覧 が確認できていたのに、

![スクリーンショット 2022-10-14 111813](https://user-images.githubusercontent.com/64347376/195752890-ada565e6-4d47-449d-93cc-2b577b96e224.png)
今 Work一覧の取得に失敗して編集・削除機能が確認できなくなってる。

![スクリーンショット 2022-10-14 115317](https://user-images.githubusercontent.com/64347376/195752896-d4978173-1083-4475-827c-d0a6ccbbf44d.png)

レビューできないよ～～ @cordx56 さん助けて～～～ 😭😭😭

2022-10-14 03:08 UTC, MogamiTsuchikawa commented
@Shimiiy VC入れる？？

2022-10-14 03:12 UTC, Shimiiy commented
VC入れない

2022-10-14 03:18 UTC, MogamiTsuchikawa commented
@Shimiiy では最低限以下のことをしましょう
- 原因をある程度予想する
  - Networkタブにてエラーを吐いているレスポンスを見てサーバーが直に吐いているエラー文を読む（これでだいたい原因わかる
- ヘルプのリクエストはどうして欲しいかを明確化する・提案する
  - コードをそちらでも見て欲しいのか（開発段階のものが動かなくて困っている場合は非常に有効・非同期的なので相手の負担も小さい）
  - VCなどでペアプロして欲しいのか（解決は早い。日時まで提案できるとベター（しないと相手が提案しないといけなくなる））

2022-10-14 07:53 UTC, Shimiiy commented
### 症状
Work一覧やMy Worksページに移動する際、
ページ自体は表示されるが、Work関連のデータを取得（GET）しようとするときに500番エラーが起こる

![スクリーンショット 2022-10-14 155507](https://user-images.githubusercontent.com/64347376/195782784-ec7f0db1-07e5-4440-b800-351e4313c91d.png)
### 原因の予想と僕がやったテスト

- backend側で構築したDBが古い？
  - masterブランチから git pull をした
  - readme.md にあるマイグレーションのコマンドを実行した
  - ⇒ でも動かない
- `auther_id` を渡しているのが悪いのか？
  - スペルミスだと認識して `author_id` に修正してほしいと頼んでいたが、
  バックエンドのコードを確認したら全て `auther` に統一されていた
  - 試しに `useWorks.ts` で `author` のスペルを `auther` に治してもう一回 yarn dev した
  - ⇒ でも動かない
- **Conoha/Wasabi のオブジェクトストレージ側で問題が起きている？**
  - **そもそも僕が今まで生成した Workデータ ってどこに行ったんだ？**
  - 500番エラーが出ていたので、無知な自分の中ではこの説が一番有力
  - 誰か環境が整っている人にオブジェクトストレージの動作確認をしてもらいたい

### 他の人にやってほしいこと
- 今回のプルリクで載っているコードを、他の人の環境で実行してほしい
- テストしてほしいこと
  - Work の追加ができるか
  - Tag の追加ができるか
  - 両者とも追加後の編集、削除ができるか
  - 追加後に一度、実行環境を落とした後、
  きちんと Work や Tag が残っているかを確認できるか
  
よろしくお願いします。

2022-10-14 09:40 UTC, MogamiTsuchikawa commented
@Shimiiy 
> backend側で構築したDBが古い？
masterブランチから git pull をした
readme.md にあるマイグレーションのコマンドを実行した
⇒ でも動かない

みるおくんを信じない前提で考えると、マイグレーションができていないんじゃないかと思います。
例えば、docker compose upした状態でmigrationしないで、単独でmigrationコマンドを走らせるなどしていませんか？

> auther_id を渡しているのが悪いのか？
スペルミスだと認識して author_id に修正してほしいと頼んでいたが、
バックエンドのコードを確認したら全て auther に統一されていた
試しに useWorks.ts で author のスペルを auther に治してもう一回 yarn dev した
⇒ でも動かない

これに関してはフロントエンド側で完結するコードなので関係ない

> Conoha/Wasabi のオブジェクトストレージ側で問題が起きている？
そもそも僕が今まで生成した Workデータ ってどこに行ったんだ？
500番エラーが出ていたので、無知な自分の中ではこの説が一番有力
誰か環境が整っている人にオブジェクトストレージの動作確認をしてもらいたい

オブジェクトストレージに問題が起きていれば本番環境でも問題が起きています。
また.envも私のと同じにしたのでオブジェクトストレージの接続設定には問題ありません。

また、500番エラーですが、バックエンド側のログで何のエラーかは出ているとは思います。

他の人にやって欲しいことに書いてあることですが、これは何を確認するためにお願いしている感じですか？（少なくとも開発した土川での環境で動いていることを考えるとあまり意味をなさないように思えます・環境の問題を解決することを諦めレビューを放棄して他の人に任せるというのであれば、それはちょっと（今後確認できないわけですし））

とりあえずVCでやりたくはない意思は確認したので、環境などの確認・調整をしたい場合は別でバックエンド側にヘルプのIssueを生やしてそちらで話しましょうか

2022-10-14 13:10 UTC, Shimiiy requested changes
@MogamiTsuchikawa 
こちらで一通りの機能のテストを行いました。

## 単体テスト
### Work
- Workの作成 OK
- Workの編集 OK
- Workの削除 × （`mywork.tsx` の 71行目をコメントアウトされているみたいですが、理由をお伺いしたいです）
### Tag
- Tag の作成 △
- Tag の編集 × （`useWorkTag.ts` にそれっぽい関数が見当たりませんでした）
- Tag の削除 △

Tagの作成、削除で△を付けた理由ですが、
リロードしないと変更がブラウザ上に反映されないというのは、
利用者側からするととても不安になってしまいます。

【新規Tag作成直後、リロード前】

![スクリーンショット 2022-10-14 214204](https://user-images.githubusercontent.com/64347376/195850220-3e9edb82-2a1b-4434-9dae-fa3cd8e13362.png)
【リロード後】

![スクリーンショット 2022-10-14 214220](https://user-images.githubusercontent.com/64347376/195850447-9c3f1ac1-783c-4798-b6f3-0b0064abac04.png)

## 結合テスト
- Tag を入れた状態で新規 Work を追加  OK
- 既存 Work に Tag を追加  OK
- Tag を複数個作成・追加したあとに 新規 Work を作成  OK
- Tag を複数個作成・追加したあとに 既存 Work を編集  ×

My Works ページまでは行けますが、
そこから既存 Work の編集ページ `work/[id].tsx` に入ると、
以下のエラー `TypeError: Cannot read properties of undefined (reading 'name')` が出ます。
新規 Work を作成するときは正常に動くので、
`[id].tsx `で、例えば引数の引き渡しが上手く行っていないのかもしれません。

![スクリーンショット 2022-10-14 205944](https://user-images.githubusercontent.com/64347376/195852675-5f089009-0e47-4ce1-b1c2-727db8be8ec3.png)

一通りのテストの様子を YouTube上 に限定公開で上げたので、Mattermost の ~digicore-team チャンネルから共有リンクを踏んでみてほしいです。
10分ほどの長さですので動画内で上手く行っている部分は飛ばしながら見てください。

2022-10-14 15:48 UTC, Shimiiy approved these changes

2022-10-14 15:56 UTC, Shimiiy approved these changes
- TypeErrorの解消を確認できました。
- 先に編集機能を実装して、**Work の削除機能はバックエンドの修正後また後日にリリースする**と伺っています。
- また、タグ追加に関する機能はとりあえず導線を切っておいて、また後日実装するということも伺っております。

以上をもって、このPRを承認します。LGTM！

2022-10-14 16:28 UTC, merged